name: MPD UI Native

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os  : [ 'ubuntu-22.04', 'mac-13', 'mac-14', 'windows-2022', 'ubuntu-22.04-arm' ]
        java: [ '21' ]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Update submodules
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Build Native with Maven
      run: mvn -B "-Pnative,browser-presenter" package -DskipTests
