name: MPD UI Native

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '21' ]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Update submodules
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Native with Maven
      run: mvn -B -Pnative,browser-presenter package
